language: cpp
os: linux
dist: bionic

install: .travis-ci/install.sh
before_script: .travis-ci/beforeScript.sh
script: .travis-ci/script.sh

after_success:
  - if [ "$COVERAGE" == "1" ]; then
      bash <(curl -s https://codecov.io/bash) -x "$GCOV";
    fi
after_failure:
  - cat build/meson-logs/testlog.txt || true;

cache:
  pip: true
  directories:
    - /tmp/coverity-scan-analysis

matrix:
  include:
    - compiler: gcc-9
      env:
        - CC=gcc-9 CXX=g++-9 COVERAGE=0 COVERITY_PROJECT_NAME=DX-MON/crunch
        - secure: "F5Sjj6am7EmjkgP3YGUe2WpLnC/UNnBXJ/aJpH3DDq1wFef7jhkNhGZvSrv6ls6AvR4WotkEU8sfEUfzs2H9W0c5rwySCEvK8u8AvTNxvHzQoBNh2BPpriVZlrHpkurFwQmzLjXomKuLy8q1dfQCwDnt+ZLrXRmxHCH0ziDgGSQ="
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-9
            - python3.7
      before_install:
        - . .travis-ci/installCoverity.sh
      before_script:
        - meson build --prefix=$HOME/.local
      script:
        - cov-build --dir cov-int ninja -C build
      after_script:
        - VERSION=`meson introspect build --projectinfo | jq -r '.["version"]'`-`git rev-parse --short HEAD`
        - tar cJf crunch.tar.xz cov-int
        - |
          curl --form token=${COVERITY_SCAN_TOKEN} \
            --form email=dx-mon@users.sourceforge.net \
            --form file=@crunch.tar.xz \
            --form version=$VERSION \
            --form description="crunch your code. Crunch is a unit testing framework written for C and C++." \
            https://scan.coverity.com/builds?project=DX-MON%2Fcrunch
      after_failure: cat cov-int/build-log.txt
      if: branch = coverityScan

env:
  global:
    - COVERAGE=1

notifications:
  email:
    on_success: change
    on_failure: change
